language: php

php:
  - 7.2
  - 7.3

before_install:
  - travis_retry composer self-update

install: composer update --prefer-source --no-interaction

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit
